apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace}}
  labels:
    role: {{ .Values.role}}
    version: {{ .Values.version }}
spec:
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: {{ .Values.serviceport }}
  selector:
    role: {{ .Values.role }}
